version: "3.9"

services:
  loki:
    build: .
    image: local/loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./data:/loki
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml:ro
    command: ["/usr/bin/loki", "-config.file=/etc/loki/local-config.yaml"]
